### ISSUE TITLE
Regular restarts needed

### ISSUE THREAD

**Issue by KaptnKirk** [Flashy-GER/ioBroker.blink4home#12]
After starting up, adapter (v0.1.1 on an Ubuntu system w/ Node.js v10.19.0) is working fine for a while. De-/activation of the system via data-point "armed" is successful. After a couple of days of regular operation, de-/activation of the system via data-point does no longer work. Re-starting the adapter usually fixes the issue.

**Comment by Flashy-GER** [comment]
Hi,
thanks for your response.
It will bie fixed in next version

**Comment by charly9898** [comment]
Since the last update in May from the js-controller to version 3.1.4 blink4home does not run anymore.
Are you working on an update?

**Comment by charly9898** [comment]
LOG
blink4home.0 | 2020-06-02 15:52:33.163 | warn | (19901) Terminated (NO_ADAPTER_CONFIG_FOUND): Without reason
blink4home.0 | 2020-06-02 15:52:33.139 | error | (19901) adapter disabled
blink4home.0 | 2020-06-02 15:52:00.823 | info | (19103) Terminated (NO_ERROR): Without reason
blink4home.0 | 2020-06-02 15:52:00.822 | info | (19103) terminating
blink4home.0 | 2020-06-02 15:52:00.814 | error | at process._tickCallback (internal/process/next_tick.js:63:19)
blink4home.0 | 2020-06-02 15:52:00.814 | error | at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
blink4home.0 | 2020-06-02 15:52:00.814 | error | at emitErrorNT (internal/streams/destroy.js:91:8)
blink4home.0 | 2020-06-02 15:52:00.814 | error | at TLSSocket.emit (events.js:198:13)
blink4home.0 | 2020-06-02 15:52:00.814 | error | at TLSSocket.socketErrorListener (_http_client.js:401:9)
blink4home.0 | 2020-06-02 15:52:00.814 | error | at ClientRequest.emit (events.js:198:13)
blink4home.0 | 2020-06-02 15:52:00.814 | error | at Request.onRequestError (/opt/iobroker/node_modules/node-blink-security/node_modules/request/request.js:878:8)
blink4home.0 | 2020-06-02 15:52:00.814 | error | at Request.emit (events.js:198:13)
blink4home.0 | 2020-06-02 15:52:00.814 | error | at self.callback (/opt/iobroker/node_modules/node-blink-security/node_modules/request/request.js:186:22)
blink4home.0 | 2020-06-02 15:52:00.814 | error | at Request.request.post [as _callback] (/opt/iobroker/node_modules/node-blink-security/lib/blink.js:328:22)
blink4home.0 | 2020-06-02 15:52:00.814 | error | (19103) Error: Authentication problem: second attempt
blink4home.0 | 2020-06-02 15:52:00.813 | error | (19103) unhandled promise rejection: Authentication problem: second attempt
blink4home.0 | 2020-06-02 15:52:00.090 | info | (19103) starting. Version 0.1.1 in /opt/iobroker/node_modules/iobroker.blink4home, node: v10.20.1, js-controller: 3.1.4
