### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by pfleiderer** [Flashy-GER/ioBroker.blink4home#18]
Wich right name an pass i got the following  error

139 | error | at processTicksAndRejections (internal/process/task_queues.js:84:21)
-- | -- | --
blink4home.0 | 2020-08-18 01:22:21.139 | error | at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
blink4home.0 | 2020-08-18 01:22:21.139 | error | at emitErrorNT (internal/streams/destroy.js:92:8)
blink4home.0 | 2020-08-18 01:22:21.139 | error | at TLSSocket.emit (events.js:315:20)
blink4home.0 | 2020-08-18 01:22:21.139 | error | at TLSSocket.socketErrorListener (_http_client.js:426:9)
blink4home.0 | 2020-08-18 01:22:21.139 | error | at ClientRequest.emit (events.js:315:20)
blink4home.0 | 2020-08-18 01:22:21.139 | error | at Request.onRequestError (/opt/iobroker/node_modules/node-blink-security/node_modules/request/request.js:878:8)
blink4home.0 | 2020-08-18 01:22:21.139 | error | at Request.emit (events.js:315:20)
blink4home.0 | 2020-08-18 01:22:21.139 | error | at self.callback (/opt/iobroker/node_modules/node-blink-security/node_modules/request/request.js:186:22)
blink4home.0 | 2020-08-18 01:22:21.139 | error | at Request._callback (/opt/iobroker/node_modules/node-blink-security/lib/blink.js:328:22)
blink4home.0 | 2020-08-18 01:22:21.139 | error | (755) Error: Authentication problem: second attempt
blink4home.0 | 2020-08-18 01:22:21.136 | error | (755) unhandled promise rejection: Authentication problem: second attempt
Unhandled | 2020-08-18 01:22:21.134 | error | promise rejection. This error originated either by throwing inside of an async function

I have seen, that ign in in Blink pp i need an additionnal 6 Digit Verificaten code snd by email.
Perhaps it will be nessesery to add this Handling too in your Adapter.

I would very much appretiate if you got this Adapter to work stable. Thank you very much in advance

**Comment by ReuDa** [comment]
The author is working on the issue. https://github.com/Flashy-GER/ioBroker.blink4home/issues/15#issuecomment-623882090

But I am also interested in the progress. Are there any news?

**Comment by t6a** [comment]
Does the connection work again?
There were some good Blink offers during Prime Day and I'd like to integrate them into ioBroker. Otherwise useless for me.

**Comment by mymeyer** [comment]
Hallo , gibt es bereits eine Lösung Ansatz dafür ? Ansonsten kann ich den Adapter auch killen.

**Comment by gmoerth** [comment]
Hallo, würde mich freuen wenn du die 2FA integrieren könntest. LG Gerhard

**Comment by mamsis** [comment]
Hallo, kommt hier noch mal ein Update zum einloggen? Sonst ist der Adapter für mich wertlos und ich lösche ihn. Bitte um kurze Rückmeldung. Danke
