### ISSUE TITLE
Adapter läßt sich nicht verbinden

### ISSUE THREAD

**Issue by mamsis** [Flashy-GER/ioBroker.blink4home#27]
Der Adapter startet, zeigt kurz grün um dann wieder rot zu werden.
Log Fehlermeldung:

<html>
<body>

link4home.0 | 2021-07-01 19:46:05.181 | error | Authentication problem: second attempt
-- | -- | -- | --
blink4home.0 | 2021-07-01 19:46:05.181 | error | Error: Authentication problem: second attempt at Request._callback (/opt/iobroker/node_modules/node-blink-security/lib/blink.js:328:22) at self.callback (/opt/iobroker/node_modules/node-blink-security/node_modules/request/request.js:186:22) at Request.emit (events.js:314:20) at Request.onRequestError (/opt/iobroker/node_modules/node-blink-security/node_modules/request/request.js:878:8) at ClientRequest.emit (events.js:314:20) at TLSSocket.socketErrorListener (_http_client.js:427:9) at TLSSocket.emit (events.js:314:20) at emitErrorNT (internal/streams/destroy.js:92:8) at emitErrorAndCloseNT (internal/streams/destroy.js:60:3) at processTicksAndRejections (internal/process/task_queues.js:84:21)
blink4home.0 | 2021-07-01 19:46:05.180 | error | unhandled promise rejection: Authentication problem: second attempt
blink4home.0 | 2021-07-01 19:46:05.179 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

</body>
</html>

was tun?

**Comment by dwm66** [comment]
Das Problem hab ich auch ...

Für mich schauts grade so aus, als ob die Basisbibliothek, nämlich node-blink-security (https://github.com/madshall/node-blink-security) da kaputt ist (anscheinend hat Blink letztes Jahr mal was an der Authentisierung geändert).

Da sagt außerdem der Maintainer, dass er kein Blink mehr hat und deswegen das gern abgeben würde. :(

Gibt da auch ne Diskussion, auch nen Pull Request der's angeblich fixt. Aber der wurde nicht eingepflegt, und hats auch nicht bis nach npm geschafft.

**Comment by mamsis** [comment]
Also funktioniert blink nicht mehr... :-(     ?

**Comment by dwm66** [comment]
Mit der npm Bibliothek gerade nicht so out of the box.
Da gibts noch was in Python ... experimentiere da grad. Man fährt halt mit der Kirche 5x ums Dorf ...

**Comment by Flashy-GER** [comment]
Hi Leute,
leider bin ich in letzter Zeit nicht dazugekommen, hier was zu machen. Ich schau mir mal den aktuellen Stand an und prüfe ob man die Authentifizierung zum Laufen bekommt.
es hat sich ja zwischenzeitlich viel getan bei den Blink Produkten.
ich zieh mir mal die Security Library auf mein Repo und schau mir mal die API an ggf. muss ich die Security Library zuerst anpassen, bevor ich hier weitermachen kann.

**Comment by dwm66** [comment]
Danke für die Mühe!

**Comment by mamsis** [comment]
Danke für Deine Mühen, würd mich freuen, wenns klappt.

**Comment by mamsis** [comment]
Bei mir klappt das Verbinden auch nicht. Was kann ich tun? Kommt noch ein Einbinden? Oder ist der Adapter wertlos?
