### ISSUE TITLE
Keine Oberfläche

### ISSUE THREAD

**Issue by daniel-lo** [Flashy-GER/ioBroker.blink4home#29]
File tab.html not found

*eine Info wäre nett .. ob der Adapter noch weiter entwickelt wird*

**Comment by daniel-lo** [comment]
Oberfläche kommt bei dem Knopf auf der Instanzen-Seite aber nicht aus der Seitenleiste .. da gibt's dann o.g. Fehler. Adapter bleibt nur kurz grün. Ich vermute irgendwas mit two-factor. VG

**Comment by daniel-lo** [comment]
<html><body>


blink4home.0 | 2022-04-03 18:10:53.405 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
blink4home.0 | 2022-04-03 18:10:53.404 | info | terminating
blink4home.0 | 2022-04-03 18:10:53.265 | info | starting.  Version 0.1.1 (non-npm: Flashy-GER/ioBroker.blink4home) in  /opt/iobroker/node_modules/iobroker.blink4home, node: v14.19.1,  js-controller: 4.0.21
blink4home.0 | 2022-04-03 18:10:52.902 | error | Cannot read property 'debug' of undefined
blink4home.0 | 2022-04-03 18:10:52.901 | error | TypeError:  Cannot read property 'debug' of undefined    at new Blink4home  (/opt/iobroker/node_modules/iobroker.blink4home/main.js:24:12)    at  Object.<anonymous>  (/opt/iobroker/node_modules/iobroker.blink4home/main.js:235:2)    at  Module._compile (internal/modules/cjs/loader.js:1085:14)    at  Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)     at Module.load (internal/modules/cjs/loader.js:950:32)    at  Function.Module._load (internal/modules/cjs/loader.js:790:12)    at  Function.executeUserEntryPoint [as runMain]  (internal/modules/run_main.js:75:12)    at  internal/main/run_main_module.js:17:47
blink4home.0 | 2022-04-03 18:10:52.899 | error | uncaught exception: Cannot read property 'debug' of undefined
blink4home.0 | 2022-04-03 18:10:21.005 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
blink4home.0 | 2022-04-03 18:10:21.003 | info | terminating
blink4home.0 | 2022-04-03 18:10:20.894 | info | starting.  Version 0.1.1 (non-npm: Flashy-GER/ioBroker.blink4home) in  /opt/iobroker/node_modules/iobroker.blink4home, node: v14.19.1,  js-controller: 4.0.21
blink4home.0 | 2022-04-03 18:10:20.501 | error | Cannot read property 'debug' of undefined
blink4home.0 | 2022-04-03 18:10:20.500 | error | TypeError:  Cannot read property 'debug' of undefined    at new Blink4home  (/opt/iobroker/node_modules/iobroker.blink4home/main.js:24:12)    at  Object.<anonymous>  (/opt/iobroker/node_modules/iobroker.blink4home/main.js:235:2)    at  Module._compile (internal/modules/cjs/loader.js:1085:14)    at  Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)     at Module.load (internal/modules/cjs/loader.js:950:32)    at  Function.Module._load (internal/modules/cjs/loader.js:790:12)    at  Function.executeUserEntryPoint [as runMain]  (internal/modules/run_main.js:75:12)    at  internal/main/run_main_module.js:17:47
blink4home.0 | 2022-04-03 18:10:20.498 | error | uncaught exception: Cannot read property 'debug' of undefined
blink4home.0 | 2022-04-03 18:09:48.492 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
blink4home.0 | 2022-04-03 18:09:48.485 | info | terminating
blink4home.0 | 2022-04-03 18:09:48.454 | info | starting.  Version 0.1.1 (non-npm: Flashy-GER/ioBroker.blink4home) in  /opt/iobroker/node_modules/iobroker.blink4home, node: v14.19.1,  js-controller: 4.0.21
blink4home.0 | 2022-04-03 18:09:47.975 | error | Cannot read property 'debug' of undefined
blink4home.0 | 2022-04-03 18:09:47.974 | error | TypeError:  Cannot read property 'debug' of undefined    at new Blink4home  (/opt/iobroker/node_modules/iobroker.blink4home/main.js:24:12)    at  Object.<anonymous>  (/opt/iobroker/node_modules/iobroker.blink4home/main.js:235:2)    at  Module._compile (internal/modules/cjs/loader.js:1085:14)    at  Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)     at Module.load (internal/modules/cjs/loader.js:950:32)    at  Function.Module._load (internal/modules/cjs/loader.js:790:12)    at  Function.executeUserEntryPoint [as runMain]  (internal/modules/run_main.js:75:12)    at  internal/main/run_main_module.js:17:47
blink4home.0 | 2022-04-03 18:09:47.972 | error | uncaught exception: Cannot read property 'debug' of undefined


</body>
</html>
